<?php

namespace App\Filament\Resources\ProductResource\Pages;

use App\Filament\Resources\ProductResource;
use App\Models\Product;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateProduct extends CreateRecord
{
    protected static string $resource = ProductResource::class;

//    before creating a new product we need to add product variations into a list of variations

protected function mutateFormDataBeforeCreate(array $data): array
{
//    get current user id logged in
    $data['user_id'] = auth()->id();
    return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
}

protected function handleRecordCreation(array $data): Model
{
//    create a new product
    $product = parent::handleRecordCreation($data);

//    create a new product variation
    foreach ($data['product_variations'] as $variation){
        $product->variations()->create($variation);
    }

    return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
}

protected function afterCreate(){

//    return parent::afterCreate(); // TODO: Change the autogenerated stub

}

}
